package ke.co.greid.entities;

// Generated Mar 23, 2015 2:25:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Block generated by hbm2java
 */
@Entity
@Table(name = "block", catalog = "hims")
public class Block implements java.io.Serializable {

	private String blockCode;
	private String blockTitle;

	public Block() {
	}

	public Block(String blockCode) {
		this.blockCode = blockCode;
	}

	public Block(String blockCode, String blockTitle) {
		this.blockCode = blockCode;
		this.blockTitle = blockTitle;
	}

	@Id
	@Column(name = "block_code", unique = true, nullable = false, length = 3)
	public String getBlockCode() {
		return this.blockCode;
	}

	public void setBlockCode(String blockCode) {
		this.blockCode = blockCode;
	}

	@Column(name = "block_title", length = 210)
	public String getBlockTitle() {
		return this.blockTitle;
	}

	public void setBlockTitle(String blockTitle) {
		this.blockTitle = blockTitle;
	}

}
