package ke.co.greid.entities;

// Generated Mar 23, 2015 2:25:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name = "chapter", catalog = "hims")
public class Chapter implements java.io.Serializable {

	private int chapterNumber;
	private String chapterTitle;

	public Chapter() {
	}

	public Chapter(int chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	public Chapter(int chapterNumber, String chapterTitle) {
		this.chapterNumber = chapterNumber;
		this.chapterTitle = chapterTitle;
	}

	@Id
	@Column(name = "chapter_number", unique = true, nullable = false)
	public int getChapterNumber() {
		return this.chapterNumber;
	}

	public void setChapterNumber(int chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	@Column(name = "chapter_title", length = 110)
	public String getChapterTitle() {
		return this.chapterTitle;
	}

	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

}
