package ke.co.greid.entities;

// Generated Mar 23, 2015 2:25:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student")
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7312093123600184985L;
	private Integer idstudent;
	private String firstName;
	private String middleName;
	private Integer age;
	private Set<Course> courses = new HashSet<Course>(0);

	public Student() {
	}

	public Student(String firstName, String middleName, Integer age,
			Set<Course> courses) {
		this.firstName = firstName;
		this.middleName = middleName;
		this.age = age;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idstudent", unique = true, nullable = false)
	public Integer getIdstudent() {
		return this.idstudent;
	}

	public void setIdstudent(Integer idstudent) {
		this.idstudent = idstudent;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "student_has_course", catalog = "hims", joinColumns = { @JoinColumn(name = "student_idstudent", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "course_idcourse", nullable = false, updatable = false) })
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
